language: c

env:
    - SMVERSION=1.4
    - SMVERSION=1.5
    - SMVERSION=1.6
    - SMVERSION=2.0
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp

script: 
    - ./spcomp in_game_audio_base.sp
    - ./spcomp in_game_audio_donator_intro.sp
    - ./spcomp in_game_audio_map_change.sp
    - ./spcomp in_game_audio_player.sp
    - ./spcomp in_game_audio_uploader.sp

after_script:
    - ls *.smx

notifications:
    email: false
