language: c

env:
    - SMVERSION=1.6
    - SMVERSION=1.7
    - SMVERSION=1.8

matrix:
    fast_finish: true
    allow_failures:
        - env: SMVERSION=1.8
    
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx
    - sudo apt-get install lib32stdc++6

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp

script: 
    - ./spcomp in_game_audio_base.sp
    - ./spcomp in_game_audio_vip_intro.sp
    - ./spcomp in_game_audio_map_change.sp
    - ./spcomp in_game_audio_player.sp

after_script:
    - ls *.smx

notifications:
    email: false
