#if defined _routes_included_
    #endinput
#endif
#define _routes_included_

#define QUERY_SONG_ROUTE "/v1/api/query_song"
#define MAP_THEME_ROUTE "/v1/api/map_theme"
#define USER_THEME_ROUTE "/v1/api/user_theme"
#define AUTHORIZE_USER_ROUTE "/v1/api/authorize_user"
#define GENERATE_LOGIN_TOKEN_ROUTE "/v1/api/generate_login_token"
#define SONGS_ROUTE "/songs"
#define NEW_SONGS_ROUTE "/songs/new"
#define DIRECTORIES_ROUTE "/directories"
#define USERS_ROUTE "/users"
#define STOP_ROUTE "/stop"
